image: rocker/geospatial # rocker/verse within

article_swissdata:
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'
  artifacts:
    paths:
      - swiss-data
    when: always

article_leafletmap:
  script:
    - R -e 'rmarkdown::render("leaflet-map/leaflet-map.Rmd")'
  artifacts:
    paths:
      - leaflet-map
    when: always

article_shdi:
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
  artifacts:
    paths:
      - shdi
    when: always

article_pokemon:
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
  artifacts:
    paths:
      - pokemon
    when: always

article_mapping:
  script:
    - R -e 'rmarkdown::render("mapping/mapping.Rmd")'
  artifacts:
    paths:
      - mapping
    when: always

article_forecasting:
  script:
    - R -e 'rmarkdown::render("forecasting/forecasting.Rmd")'
  artifacts:
    paths:
      - forecasting
    when: always
