image: rocker/geospatial # rocker/verse within

check:
  stage: check_swissdata
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'

check:
  stage: check_leafletmap
  script:
    - R -e 'rmarkdown::render("leaflet-map/article.Rmd")'

check:
  stage: check_shdi
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'

check:
  stage: check_pokemon
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
