# CI for selected articles
# the articles /bond, /tennis and /cooking are not fully reproducibles

#build_image:
  #image: docker:git
  #services:
  #- docker:dind
  #script:
    #- docker login -u lgnbhl -p $CI_BUILD_TOKEN registry.gitlab.com
    #- docker build -t registry.gitlab.com/lgnbhl/blogposts/binder_blogposts .
    #- docker push registry.gitlab.com/lgnbhl/blogposts/binder_blogposts
  #only:
    #- master

article_swissdata:
  image: rocker/geospatial # rocker/verse within
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'
  artifacts:
    paths:
      - swiss-data
    when: always

article_leafletmap:
  image: rocker/geospatial
  script:
    - R -e 'rmarkdown::render("leaflet-map/leaflet-map.Rmd")'
  artifacts:
    paths:
      - leaflet-map
    when: always

article_shdi:
  image: rocker/geospatial
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
  artifacts:
    paths:
      - shdi
    when: always

article_pokemon:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
  artifacts:
    paths:
      - pokemon
    when: always

#article_cooking:
  #script:
    #- R -e 'rmarkdown::render("cooking/cooking.Rmd")'
  #artifacts:
    #paths:
      #- cooking
    #when: always

article_mapping:
  image: rocker/geospatial
  script:
    - R -e 'rmarkdown::render("mapping/mapping.Rmd")'
  artifacts:
    paths:
      - mapping
    when: always

article_forecasting:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("forecasting/forecasting.Rmd")'
  artifacts:
    paths:
      - forecasting
    when: always

article_olympics:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("olympics/olympics.Rmd")'
  artifacts:
    paths:
      - olympics
    when: always

article_network:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("network/network.Rmd")'
  artifacts:
    paths:
      - network
    when: always

article_movies:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("movies/movies.Rmd")'
  artifacts:
    paths:
      - movies
    when: always

#article_tennis:
  #script:
    #- R -e 'rmarkdown::render("tennis/tennis.Rmd")'
  #artifacts:
    #paths:
      #- tennis
    #when: always

#article_bond:
  #script:
    #- R -e 'rmarkdown::render("bond/bond.Rmd")'
  #artifacts:
    #paths:
      #- bond
    #when: always

article_orwell:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("orwell/orwell.Rmd")'
  artifacts:
    paths:
      - orwell
    when: always

article_marvel:
  image: rocker/verse
  script:
    - R -e 'rmarkdown::render("marvel/marvel.Rmd")'
  artifacts:
    paths:
      - marvel
    when: always
