image: rocker/geospatial # rocker/verse within

stages:
  - check

check:
  stage: check
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")' > swiss-data.html
  artifacts:
    paths:
    - swiss-data.html

#check:
  #stage: check
  #script:
    #- R -e 'rmarkdown::render("leaflet-map/article.Rmd")'

#check:
  #stage: check
  #script:
    #- R -e 'rmarkdown::render("shdi/shdi.Rmd")'

#check:
  #stage: check
  #script:
    #- R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
