image: rocker/geospatial # rocker/verse within

article_swissdata:
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'
  artifacts:
    paths:
      - swiss-data
    when: always

article_leafletmap:
  script:
    - R -e 'rmarkdown::render("leaflet-map/leaflet-map.Rmd")'
  artifacts:
    paths:
      - leaflet-map
    when: always

article_shdi:
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
  artifacts:
    paths:
      - shdi
    when: always

article_pokemon:
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
  artifacts:
    paths:
      - pokemon
    when: always

#article_cooking:
  #script:
    #- R -e 'rmarkdown::render("cooking/cooking.Rmd")'
  #artifacts:
    #paths:
      #- cooking
    #when: always

article_mapping:
  script:
    - R -e 'rmarkdown::render("mapping/mapping.Rmd")'
  artifacts:
    paths:
      - mapping
    when: always

article_forecasting:
  script:
    - R -e 'rmarkdown::render("forecasting/forecasting.Rmd")'
  artifacts:
    paths:
      - forecasting
    when: always

article_olympics:
  script:
    - R -e 'rmarkdown::render("olympics/olympics.Rmd")'
  artifacts:
    paths:
      - olympics
    when: always

article_network:
  script:
    - R -e 'rmarkdown::render("network/network.Rmd")'
  artifacts:
    paths:
      - network
    when: always

article_movies:
  script:
    - R -e 'rmarkdown::render("movies/movies.Rmd")'
  artifacts:
    paths:
      - movies
    when: always

#article_tennis:
  #script:
    #- R -e 'rmarkdown::render("tennis/tennis.Rmd")'
  #artifacts:
    #paths:
      #- tennis
    #when: always

#article_bond:
  #script:
    #- R -e 'rmarkdown::render("bond/bond.Rmd")'
  #artifacts:
    #paths:
      #- bond
    #when: always

article_orwell:
  script:
    - R -e 'rmarkdown::render("orwell/orwell.Rmd")'
  artifacts:
    paths:
      - orwell
    when: always

article_marvel:
  script:
    - R -e 'rmarkdown::render("marvel/marvel.Rmd")'
  artifacts:
    paths:
      - marvel
    when: always
