image: rocker/geospatial # rocker/verse within

swissdata:
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'
  artifacts:
    paths:
      - swiss-data
    when: always

leafletmap:
  script:
    - R -e 'rmarkdown::render("leaflet-map/leaflet-map.Rmd")'
  artifacts:
    paths:
      - leaflet-map
    when: always

shdi:
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
  artifacts:
    paths:
      - shdi
    when: always

pokemon:
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
  artifacts:
    paths:
      - pokemon
    when: always
