image: rocker/geospatial # rocker/verse within

stages:
  - check_swissdata
  - check_leafletmap
  - check_shdi
  - check_pokemon

test:
  stage: check_swissdata
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'
  artifacts:
    paths:
      - swiss-data
    when: always

test:
  stage: check_leafletmap
  script:
    - R -e 'rmarkdown::render("leaflet-map/leaflet-map.Rmd")'
  artifacts:
    paths:
      - leaflet-map
    when: always

test:
  stage: check_shdi
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
  artifacts:
    paths:
      - shdi
    when: always

test:
  stage: check_pokemon
  script:
    - R -e 'rmarkdown::render("pokemon/pokemon.Rmd")'
  artifacts:
    paths:
      - pokemon
    when: always
