image: rocker/verse

stages:
  - check_swissdata
  - check_leafletmap
  - check_shdi

check:
  stage: check_swissdata
  script:
    - R -e 'rmarkdown::render("swiss-data/swiss-data.Rmd")'

check:
  stage: check_leafletmap
  image: rocker/geospatial
  script:
    - R -e 'rmarkdown::render("leaflet-map/article.Rmd")'

check:
  stage: check_shdi
  script:
    - R -e 'rmarkdown::render("shdi/shdi.Rmd")'
